routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FirebaseController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\BackendController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\StaffController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('home/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\FrontEndController@changeLang']);

Route::get('/mary', function () {
    return view('welcome');
});

Route::get('/hitit',[CityController::class,'sayhitit'])->name('hit.it');



Route::get('firebase', [FirebaseController::class, 'index']);
// Route::view('customers','customers'); 

//contact start
Route::resource('city', CityController::class);
Route::resource('contact', ContactController::class);



Route::group(['middleware' =>[ 'auth','role:customer']], function () {
    Route::get('/', function () {
    return view('FrontEnd_Template');
    });

//user route
Route::get('/user/order', [OrderController::class, 'orderCreatedByUser'])->name('user.order.create');
Route::get('/user/info', [FrontEndController::class, 'userInfo'])->name('user.info');
Route::get('/user/address/list', [FrontEndController::class, 'userAddressList'])->name('user.address.list');
Route::get('/user/order/list', [FrontEndController::class, 'userOrderList'])->name('user.order.list');

// order search --------
Route::post('/order/search', [FrontEndController::class, 'orderSearch'])->name('order.search');
Route::get('/user/home', [FrontEndController::class, 'userHomepage'])->name('user.home');

Route::get('/get/orders/{status}',[FrontEndController::class,'userOrderbyStatus'])->name('user.order.status');




Route::post('/order/store', [OrderController::class, 'orderStoredByUser'])->name('user.order.store');

Route::get('/order/{id}', [OrderController::class, 'orderDetail'])->name('user.order.detail');
// for user
Route::delete('/order/{id}', [OrderController::class, 'orderDestroy'])->name('order.delete');


    // excel import/export
Route::get('file/import/read',[OrderController::class,'UserImportfileReading'])->name('user.file.reading');
Route::get('file-import-export', [OrderController::class, 'fileImportExport']);
Route::post('file-import', [OrderController::class, 'fileImport'])->name('file-import');
Route::get('file-export', [OrderController::class, 'fileExport'])->name('file-export');
});



///admin start---------------------------------


Route::group(['middleware' => ['auth:web,staff','role:admin|staff','permission:order-status']],function(){

Route::post('/s/change/',[OrderController::class,'changeOrderStatus'])->name('order.status.change');

});







Route::group(['prefix'=>'admin','middleware'=>['auth:web,staff']],function () {




    Route::get('/dashboard', [BackendController::class, 'dashboard'])->name('dashboard.index');

    // customer start
    Route::prefix('/orders')->group(function () {

        Route::get('/', [BackendController::class, 'orderIndex'])->name('admin.order.list');


        Route::get('/create/new', [BackendController::class, 'orderCreate'])->name('admin.order.create');

        Route::get('/getAddressByuid/{id}', [BackendController::class, 'getAddressByuid'])->name('admin.order.getAddress');

        Route::get('/detail/{id}',[OrderController::class,'orderDetailByAdmin'])->name('admin.order.detail');

         Route::get('/edit/{id}',[OrderController::class,'orderEditByAdmin'])->name('admin.order.edit');

         Route::put('/update/{id}',[OrderController::class,'orderUpdateByAdmin'])->name('admin.order.update');

        Route::delete('/delete/{id}',[OrderController::class,'orderDeleteByAdmin'])->name('admin.order.destroy');

        Route::post('/date/filter',[OrderController::class,'orderDateFilter'])->name('admin.order.date.filter');

        Route::get('/import',[BackendController::class,'orderImport'])->name('admin.order.import');

         Route::post('/readExcel',[BackendController::class,'readExcel'])->name('admin.order.readExcel');

         Route::post('/importExcel',[BackendController::class,'importExcel'])->name('admin.order.importExcel');
    });

    Route::prefix('/address')->group(function () {
        Route::get('/create/{id}', [ContactController::class, 'addressCreateByUid'])->name('admin.address.createbyui');


        Route::get('/edit/{id}', [ContactController::class, 'addressEdit'])->name('admin.address.edit');

        Route::get('/getall/{id}', [ContactController::class, 'addressbyuserid'])->name('admin.userid.addresses');


    });

    // customer start
    Route::prefix('/customer')->group(function () {
        Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
    });

    Route::prefix('/rp')->group(function(){
        Route::get('/',[BackendController::class,'roleIndex'])->name('admin.rp.index');
        Route::get('/r/create',[BackendController::class,'roleCreate'])->name('admin.rp.role.create');
        Route::post('/r/store',[BackendController::class,'roleStore'])->name('admin.rp.role.store');
         Route::get('/r/show/{id}',[BackendController::class,'roleShow'])->name('admin.rp.role.show');
         Route::get('/r/edit/{id}',[BackendController::class,'roleEdit'])->name('admin.rp.role.edit');
         Route::put('/r/update/{id}',[BackendController::class,'roleUpdate'])->name('admin.rp.role.update');

         Route::delete('/r/destroy/{id}',[BackendController::class,'roleDelete'])->name('admin.rp.role.delete');


         Route::get('/p',[BackendController::class,'permissionIndex'])->name('admin.rp.p.index');

         Route::post('/p/store',[BackendController::class,'permissionStore'])->name('admin.rp.p.store');

         Route::put('/p/update/{id}',[BackendController::class,'permissionUpdate'])->name('admin.rp.p.update');

         Route::delete('/p/delete/{id}',[BackendController::class,'permissionDelete'])->name('admin.rp.p.delete');

    });

    //order import


});

//change order for admin and staff

// Route::group(['middleware'=>['auth','role:admin|staff','permission:publish order-status']],function () {
//         Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
//     })



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');




require __DIR__ . '/auth.php';

// auth redireact

Route::get('/redirect', [ResponseController::class, 'index']);

Route::resource('staff',StaffController::class);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/Backend_Template.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Tables - SB Admin</title>
        <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css
" rel="stylesheet" />
        <link href="{{ asset('template/css/styles.css') }}" rel="stylesheet" />
        <link href="{{ asset('template/css/backend.css') }}" rel="stylesheet" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

        <style type="text/css">
            .my-td {
                max-width: 120px;
                
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: wrap;
                
            }

            .my-td:hover {
                overflow: visible;
                white-space: unset;
            }
        </style>

    </head>

    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Shipper Admin </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!">
                <i class="fas fa-bars"></i>
            </button>
            <!-- Navbar Search-->
            <form class="
                    d-none d-md-inline-block
                    form-inline
                    ms-auto
                    me-0 me-md-3
                    my-2 my-md-0
                ">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i
                    ></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <!-- <li><a class="dropdown-item" href="#!">Settings</a></li> -->
                       <!--  <li>
                            <a class="dropdown-item" href="#!">Activity Log</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li> -->
                        <li>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <button type="submit" class="dropdown-item">
                                    {{ __('Log Out') }}
                                </button>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{{route('dashboard.index')}}">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-tachometer-alt"></i>
                                </div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-columns"></i>
                                </div>
                                Orders
                                <div class="sb-sidenav-collapse-arrow">
                                    <i class="fas fa-angle-down"></i>
                                </div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{{ route('admin.order.list') }}">
                                        Lists
                                    </a>
                                    <a class="nav-link" href="{{ route('admin.order.create') }}">
                                        New Orders
                                    </a>
                                    <a class="nav-link" href="{{route('admin.order.import')}}">
                                        Import Excel Order
                                    </a>
                                </nav>
                            </div>
                            
                            <div class="sb-sidenav-menu-heading">Users</div>
                            <a class="nav-link" href="{{route('staff.index')}}">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-chart-area"></i>
                                </div>
                                Staff
                            </a>
                            <a class="nav-link" href="{{route('admin.customer.index')}}">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-table"></i>
                                </div>
                                Customer
                            </a>
                            <div class="sb-sidenav-menu-heading">Permission Setting</div>
                            <a class="nav-link" href="{{route('admin.rp.index')}}">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-chart-area"></i>
                                </div>
                                Role
                            </a>
                            <a class="nav-link" href="{{route('admin.rp.p.index')}}">
                                <div class="sb-nav-link-icon">
                                    <i class="fas fa-table"></i>
                                </div>
                                Permission
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        @if(Auth::guard('web')->check())
                            Hello {{Auth::guard('web')->user()->name}}
                        @elseif(Auth::guard('staff')->check())
                            Hello {{Auth::guard('staff')->user()->name}}
                        @endif
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>@yield('mainContent')</main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="
                                d-flex
                                align-items-center
                                justify-content-between
                                small
                            ">
                            <div class="text-muted">
                                Copyright &copy; Your Website 2021
                            </div>
                            <div>
                                <a href="#">Privacy Policy</a> &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        <script src="{{ asset('template/js/jquery.min.js') }}"></script>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('template/js/scripts.js') }}"></script>

        <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>

        <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        
         


        <script>
            $("#datatablesSimple").DataTable();

            $.ajaxSetup({
                headers: {
                    "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr(
                        "content"
                    ),
                },
            });
        </script>
        @yield('script')
    </body>

</html>

resources/views/FrontEnd_Template.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Tables - SB Admin</title>
        <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet" />

        <link href="{{ asset('template/css/styles.css') }}" rel="stylesheet" />
        <link href="{{ asset('template/css/frontend.css') }}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/css/intlTelInput.min.css" rel="stylesheet"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/intlTelInput.min.js"></script>
    </head>

    <body class="sb-nav-fixed" style="background-color: #eeeded">
        <nav class="navbar navbar-nav-scroll fixed-bottom navbar-dark bg-light" style="margin-top: -50px">
            <div class="container-fluid mynav">
                <a class="btn btn-default mynav-link" href="{{ route('user.home') }}">
                    <i class="fas fa-home"></i>
                    <span>{{ __('HOME') }}</span>
                </a>
                <a href="{{ route('user.order.list') }}" class="btn btn-default mynav-link">
                    <i class="fas fa-clipboard"></i>
                    <span>{{__('Order')}}</span>
                </a>
                <a href="{{ route('user.info') }}" class="btn btn-default mynav-link">
                    <i class="fas fa-user"></i>
                    <span>{{__('Info')}}</span>
                </a>
            </div>
        </nav>
        <!-- banner start -->

        <div style="max-height: 100vh; margin-bottom: 20vh">
            @yield('Manicontent')
        </div>

        <script src="{{ asset('template/js/jquery.min.js') }}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{{ asset('template/js/scripts.js') }}"></script>
        <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>

        <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
        <script src="{{
                asset('template/js/datatables-simple-demo.js')
            }}"></script>
        <script>
            //$('select').selectpicker();

            $.ajaxSetup({
                headers: {
                    "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr(
                        "content"
                    ),
                },
            });
        </script>
        @yield('script')
    </body>

</html>

resources/views/auth.blade.php
<html>
<head>
    <title>Laravel Phone Number Authentication using Firebase - ItSolutionStuff.com</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
  
<div class="container">
    <h1>Laravel Phone Number Authentication using Firebase - ItSolutionStuff.com</h1>
  
    <div class="alert alert-danger" id="error" style="display: none;"></div>
  
    <div class="card">
      <div class="card-header">
        Enter Phone Number
      </div>
      <div class="card-body">
  
        <div class="alert alert-success" id="sentSuccess" style="display: none;"></div>
  
        <form>
            <label>Phone Number:</label>
            <input type="text" id="number" class="form-control" placeholder="+91********">
            <div id="recaptcha-container"></div>
            <button type="button" class="btn btn-success" onclick="phoneSendAuth();">SendCode</button>
        </form>
      </div>
    </div>
      
    <div class="card" style="margin-top: 10px">
      <div class="card-header">
        Enter Verification code
      </div>
      <div class="card-body">
  
        <div class="alert alert-success" id="successRegsiter" style="display: none;"></div>
  
        <form>
            <input type="text" id="verificationCode" class="form-control" placeholder="Enter verification code">
            <button type="button" class="btn btn-success" onclick="codeverify();">Verify code</button>
  
        </form>
      </div>
    </div>
  
</div>
  
<script src="https://www.gstatic.com/firebasejs/6.0.2/firebase.js"></script>
  
<script>
      
  var  firebaseConfig = {
  apiKey: "AIzaSyBVHlZ-7hKSmTXi1shjyqtP3pfh-wVS328",
  authDomain: "deliveryprj-8176e.firebaseapp.com",
  databaseURL: "https://deliveryprj-8176e-default-rtdb.firebaseio.com",
  projectId: "deliveryprj-8176e",
  storageBucket: "deliveryprj-8176e.appspot.com",
  messagingSenderId: "144627415309",
  appId: "1:144627415309:web:59d5b920329fa9aa19d844",
  measurementId: "G-56F3E2Z4WG"
};
    
  firebase.initializeApp(firebaseConfig);
</script>
  
<script type="text/javascript">
  
    window.onload=function () {
      render();
    };
  
    function render() {
        window.recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha-container');
        recaptchaVerifier.render();
    }
  
    function phoneSendAuth() {
           
        var number = $("#number").val();
          
        firebase.auth().signInWithPhoneNumber(number,window.recaptchaVerifier).then(function (confirmationResult) {
              
            window.confirmationResult=confirmationResult;
            coderesult=confirmationResult;
            console.log(coderesult);
  
            $("#sentSuccess").text("Message Sent Successfully.");
            $("#sentSuccess").show();
              
        }).catch(function (error) {
            $("#error").text(error.message);
            $("#error").show();
        });
  
    }
  
    function codeverify() {
  
        var code = $("#verificationCode").val();
  
        coderesult.confirm(code).then(function (result) {
            var user=result.user;
            console.log(user);
  
            $("#successRegsiter").text("you are register Successfully.");
            $("#successRegsiter").show();
  
        }).catch(function (error) {
            $("#error").text(error.message);
            $("#error").show();
        });
    }
  
</script>
  
</body>
</html>

resources/views/customers.blade.php
hello world

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>