routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FirebaseController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\BackendController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\StaffController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('home/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\FrontEndController@changeLang']);

Route::get('/mary', function () {
    return view('welcome');
});

Route::get('/hitit',[CityController::class,'sayhitit'])->name('hit.it');



Route::get('firebase', [FirebaseController::class, 'index']);
// Route::view('customers','customers'); 

//contact start
Route::resource('city', CityController::class);
Route::resource('contact', ContactController::class);



Route::group(['middleware' =>[ 'auth','role:customer']], function () {
    Route::get('/', function () {
    return view('FrontEnd_Template');
    });

//user route
Route::get('/user/order', [OrderController::class, 'orderCreatedByUser'])->name('user.order.create');
Route::get('/user/info', [FrontEndController::class, 'userInfo'])->name('user.info');
Route::get('/user/address/list', [FrontEndController::class, 'userAddressList'])->name('user.address.list');
Route::get('/user/order/list', [FrontEndController::class, 'userOrderList'])->name('user.order.list');

// order search --------
Route::post('/order/search', [FrontEndController::class, 'orderSearch'])->name('order.search');
Route::get('/user/home', [FrontEndController::class, 'userHomepage'])->name('user.home');

Route::get('/get/orders/{status}',[FrontEndController::class,'userOrderbyStatus'])->name('user.order.status');




Route::post('/order/store', [OrderController::class, 'orderStoredByUser'])->name('user.order.store');

Route::get('/order/{id}', [OrderController::class, 'orderDetail'])->name('user.order.detail');
// for user
Route::delete('/order/{id}', [OrderController::class, 'orderDestroy'])->name('order.delete');


    // excel import/export
Route::get('file/import/read',[OrderController::class,'UserImportfileReading'])->name('user.file.reading');
Route::get('file-import-export', [OrderController::class, 'fileImportExport']);
Route::post('file-import', [OrderController::class, 'fileImport'])->name('file-import');
Route::get('file-export', [OrderController::class, 'fileExport'])->name('file-export');
});



///admin start---------------------------------


Route::group(['middleware' => ['auth:web,staff','role:admin|staff','permission:order-status']],function(){

Route::post('/s/change/',[OrderController::class,'changeOrderStatus'])->name('order.status.change');

});







Route::group(['prefix'=>'admin','middleware'=>['auth:web,staff']],function () {




    Route::get('/dashboard', [BackendController::class, 'dashboard'])->name('dashboard.index');

    // customer start
    Route::prefix('/orders')->group(function () {

        Route::get('/', [BackendController::class, 'orderIndex'])->name('admin.order.list');


        Route::get('/create/new', [BackendController::class, 'orderCreate'])->name('admin.order.create');

        Route::get('/getAddressByuid/{id}', [BackendController::class, 'getAddressByuid'])->name('admin.order.getAddress');

        Route::get('/detail/{id}',[OrderController::class,'orderDetailByAdmin'])->name('admin.order.detail');

         Route::get('/edit/{id}',[OrderController::class,'orderEditByAdmin'])->name('admin.order.edit');

         Route::put('/update/{id}',[OrderController::class,'orderUpdateByAdmin'])->name('admin.order.update');

        Route::delete('/delete/{id}',[OrderController::class,'orderDeleteByAdmin'])->name('admin.order.destroy');

        Route::post('/date/filter',[OrderController::class,'orderDateFilter'])->name('admin.order.date.filter');

        Route::get('/import',[BackendController::class,'orderImport'])->name('admin.order.import');

         Route::post('/readExcel',[BackendController::class,'readExcel'])->name('admin.order.readExcel');

         Route::post('/importExcel',[BackendController::class,'importExcel'])->name('admin.order.importExcel');
    });

    Route::prefix('/address')->group(function () {
        Route::get('/create/{id}', [ContactController::class, 'addressCreateByUid'])->name('admin.address.createbyui');


        Route::get('/edit/{id}', [ContactController::class, 'addressEdit'])->name('admin.address.edit');

        Route::get('/getall/{id}', [ContactController::class, 'addressbyuserid'])->name('admin.userid.addresses');


    });

    // customer start
    Route::prefix('/customer')->group(function () {
        Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
    });

    Route::prefix('/rp')->group(function(){
        Route::get('/',[BackendController::class,'roleIndex'])->name('admin.rp.index');
        Route::get('/r/create',[BackendController::class,'roleCreate'])->name('admin.rp.role.create');
        Route::post('/r/store',[BackendController::class,'roleStore'])->name('admin.rp.role.store');
         Route::get('/r/show/{id}',[BackendController::class,'roleShow'])->name('admin.rp.role.show');
         Route::get('/r/edit/{id}',[BackendController::class,'roleEdit'])->name('admin.rp.role.edit');
         Route::put('/r/update/{id}',[BackendController::class,'roleUpdate'])->name('admin.rp.role.update');

         Route::delete('/r/destroy/{id}',[BackendController::class,'roleDelete'])->name('admin.rp.role.delete');


         Route::get('/p',[BackendController::class,'permissionIndex'])->name('admin.rp.p.index');

         Route::post('/p/store',[BackendController::class,'permissionStore'])->name('admin.rp.p.store');

         Route::put('/p/update/{id}',[BackendController::class,'permissionUpdate'])->name('admin.rp.p.update');

         Route::delete('/p/delete/{id}',[BackendController::class,'permissionDelete'])->name('admin.rp.p.delete');

    });

    //order import


});

//change order for admin and staff

// Route::group(['middleware'=>['auth','role:admin|staff','permission:publish order-status']],function () {
//         Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
//     })



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');




require __DIR__ . '/auth.php';

// auth redireact

Route::get('/redirect', [ResponseController::class, 'index']);

Route::resource('staff',StaffController::class);

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;


class City extends Model
{
    use HasFactory,SoftDeletes;
    protected $fillable=['name','abb'];

    public function contacts(){
        return $this->hasMany(Contact::class,'address_id');
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\City;
use App\Events\NewComment;
use Auth;

class CityController extends Controller
{
    public function sayhitit(){

        dd(Auth::guard('staff')->user()->name);
        event(new NewComment('hello world'));
        return back();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities=City::all();
        //dd($cities);
        return view('admin.city.index',compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       
        City::create([
            'name'=>$request->city,
            'abb'=>$request->abb,
        ]);
        return redirect()->route('city.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $city=City::find($id);
        $city->name=$request->ecity;
        $city->abb=$request->eabb;
        $city->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       // dd($id);
        $city=City::find($id);
        $city->delete();
        return back();
    }
}

resources/views/admin/city/index.blade.php
@extends('Backend_Template') @section('mainContent')
<div class="container-fluid px-4">
    <h1 class="mt-4">Tables</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item">
            <a href="{{route('dashboard.index')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">City</li>
    </ol>
    <div class="card mb-4" id="addNewForm">
        <div class="card-header">Add New City</div>
        <div class="card-body">
            <form action="{{ route('city.store') }}" method="post">
                @csrf
                <div class="mb-3 row">
                    <div class="col">
                        <label for="city" class="form-label">Name</label>
                        <input
                            type="text"
                            name="city"
                            class="form-control"
                            id="city"
                        />
                    </div>
                    <div class="col">
                        <label for="city" class="form-label">Abb</label>
                        <input
                            type="text"
                            name="abb"
                            class="form-control"
                            id="abb"
                        />
                    </div>
                    <div class="col d-flex align-items-end">

                        <input
                            type="submit"

                            class="btn btn-primary  float-end form-control"
                            value="Add Now"
                            placeholder="add now!"
                        />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-4 d-none" id="editForm">
        <div class="card-header">Edit City</div>
        <div class="card-body">
            <form method="post" id="editFormSubmit">
                @csrf @method('PATCH')
                <div class="mb-3 row">
                    <div class="col">
                        <label for="ecity" class="form-label">Name</label>
                        <input
                            type="text"
                            name="ecity"
                            class="form-control"
                            id="ecity"
                        />
                    </div>
                    <div class="col">
                        <label for="eabb" class="form-label">Abb</label>
                        <input
                            type="text"
                            name="eabb"
                            class="form-control"
                            id="eabb"
                        />
                    </div>
                    <div class="col d-flex align-items-end">

                        <input
                            type="submit"

                            class="btn btn-primary  float-end form-control"
                            value="Add Now"
                            placeholder="Update now!"
                        />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header mytable-card-header">
            <span>
                <i class="fas fa-table me-1"></i>
                DataTable Example
            </span>
            <!-- <a href="#staticBackdrop" class="nav-link" data-bs-toggle="modal"
                >New City</a
            > -->
        </div>
        <div class="card-body table-responsive">
            <table class="table " id="datatablesSimple">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                     
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @php $i=1; @endphp @foreach($cities as $city)

                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$city->name}}({{$city->abb}})</td>
                         
                        <td>
                            <button
                                class="btn btn-warning btn-edit"
                                data-id="{{$city->id}}"
                                data-name="{{$city->name}}"
                                data-abb="{{$city->abb}}"
                            >
                                Edit
                            </button>
                            <form
                                style="display: inline"
                                method="POST"
                                action="{{ route('city.destroy',$city->id) }}"
                            >
                                @csrf @method('delete')

                                <button type="submit" class="btn btn-danger">
                                    {{ __("Delete") }}
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection @section('script')
<script>
    $(document).ready(function () {
        $(".btn-edit").click(function (e) {
            let id = $(this).data("id");
            let name = $(this).data("name");
            let abb=$(this).data("abb");
            $("#addNewForm").addClass("d-none");
            $("#editForm").removeClass("d-none");
            $('#editForm input[name="ecity"]').val(name);
            $('#editForm input[name="eabb"]').val(abb);
            let url = "{{route('city.update',':id')}}";
            url = url.replace(":id", id);
            $("#editFormSubmit").attr("action", url);
        });
    });
</script>
@endsection