routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FirebaseController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\BackendController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\StaffController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('home/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\FrontEndController@changeLang']);

Route::get('/mary', function () {
    return view('welcome');
});

Route::get('/hitit',[CityController::class,'sayhitit'])->name('hit.it');



Route::get('firebase', [FirebaseController::class, 'index']);
// Route::view('customers','customers'); 

//contact start
Route::resource('city', CityController::class);
Route::resource('contact', ContactController::class);



Route::group(['middleware' =>[ 'auth','role:customer']], function () {
    Route::get('/', function () {
    return view('FrontEnd_Template');
    });

//user route
Route::get('/user/order', [OrderController::class, 'orderCreatedByUser'])->name('user.order.create');
Route::get('/user/info', [FrontEndController::class, 'userInfo'])->name('user.info');
Route::get('/user/address/list', [FrontEndController::class, 'userAddressList'])->name('user.address.list');
Route::get('/user/order/list', [FrontEndController::class, 'userOrderList'])->name('user.order.list');

// order search --------
Route::post('/order/search', [FrontEndController::class, 'orderSearch'])->name('order.search');
Route::get('/user/home', [FrontEndController::class, 'userHomepage'])->name('user.home');

Route::get('/get/orders/{status}',[FrontEndController::class,'userOrderbyStatus'])->name('user.order.status');




Route::post('/order/store', [OrderController::class, 'orderStoredByUser'])->name('user.order.store');

Route::get('/order/{id}', [OrderController::class, 'orderDetail'])->name('user.order.detail');
// for user
Route::delete('/order/{id}', [OrderController::class, 'orderDestroy'])->name('order.delete');


    // excel import/export
Route::get('file/import/read',[OrderController::class,'UserImportfileReading'])->name('user.file.reading');
Route::get('file-import-export', [OrderController::class, 'fileImportExport']);
Route::post('file-import', [OrderController::class, 'fileImport'])->name('file-import');
Route::get('file-export', [OrderController::class, 'fileExport'])->name('file-export');
});



///admin start---------------------------------


Route::group(['middleware' => ['auth:web,staff','role:admin|staff','permission:order-status']],function(){

Route::post('/s/change/',[OrderController::class,'changeOrderStatus'])->name('order.status.change');

});







Route::group(['prefix'=>'admin','middleware'=>['auth:web,staff']],function () {




    Route::get('/dashboard', [BackendController::class, 'dashboard'])->name('dashboard.index');

    // customer start
    Route::prefix('/orders')->group(function () {

        Route::get('/', [BackendController::class, 'orderIndex'])->name('admin.order.list');


        Route::get('/create/new', [BackendController::class, 'orderCreate'])->name('admin.order.create');

        Route::get('/getAddressByuid/{id}', [BackendController::class, 'getAddressByuid'])->name('admin.order.getAddress');

        Route::get('/detail/{id}',[OrderController::class,'orderDetailByAdmin'])->name('admin.order.detail');

         Route::get('/edit/{id}',[OrderController::class,'orderEditByAdmin'])->name('admin.order.edit');

         Route::put('/update/{id}',[OrderController::class,'orderUpdateByAdmin'])->name('admin.order.update');

        Route::delete('/delete/{id}',[OrderController::class,'orderDeleteByAdmin'])->name('admin.order.destroy');

        Route::post('/date/filter',[OrderController::class,'orderDateFilter'])->name('admin.order.date.filter');

        Route::get('/import',[BackendController::class,'orderImport'])->name('admin.order.import');

         Route::post('/readExcel',[BackendController::class,'readExcel'])->name('admin.order.readExcel');

         Route::post('/importExcel',[BackendController::class,'importExcel'])->name('admin.order.importExcel');
    });

    Route::prefix('/address')->group(function () {
        Route::get('/create/{id}', [ContactController::class, 'addressCreateByUid'])->name('admin.address.createbyui');


        Route::get('/edit/{id}', [ContactController::class, 'addressEdit'])->name('admin.address.edit');

        Route::get('/getall/{id}', [ContactController::class, 'addressbyuserid'])->name('admin.userid.addresses');


    });

    // customer start
    Route::prefix('/customer')->group(function () {
        Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
    });

    Route::prefix('/rp')->group(function(){
        Route::get('/',[BackendController::class,'roleIndex'])->name('admin.rp.index');
        Route::get('/r/create',[BackendController::class,'roleCreate'])->name('admin.rp.role.create');
        Route::post('/r/store',[BackendController::class,'roleStore'])->name('admin.rp.role.store');
         Route::get('/r/show/{id}',[BackendController::class,'roleShow'])->name('admin.rp.role.show');
         Route::get('/r/edit/{id}',[BackendController::class,'roleEdit'])->name('admin.rp.role.edit');
         Route::put('/r/update/{id}',[BackendController::class,'roleUpdate'])->name('admin.rp.role.update');

         Route::delete('/r/destroy/{id}',[BackendController::class,'roleDelete'])->name('admin.rp.role.delete');


         Route::get('/p',[BackendController::class,'permissionIndex'])->name('admin.rp.p.index');

         Route::post('/p/store',[BackendController::class,'permissionStore'])->name('admin.rp.p.store');

         Route::put('/p/update/{id}',[BackendController::class,'permissionUpdate'])->name('admin.rp.p.update');

         Route::delete('/p/delete/{id}',[BackendController::class,'permissionDelete'])->name('admin.rp.p.delete');

    });

    //order import


});

//change order for admin and staff

// Route::group(['middleware'=>['auth','role:admin|staff','permission:publish order-status']],function () {
//         Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
//     })



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');




require __DIR__ . '/auth.php';

// auth redireact

Route::get('/redirect', [ResponseController::class, 'index']);

Route::resource('staff',StaffController::class);

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
 use Illuminate\Foundation\Auth\User as Authenticatable;
 use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class Staff extends Authenticatable
{
    use HasFactory,HasRoles, Notifiable;
    protected $table='staffs';
    protected $guard='staff';
    protected $guard_name="staff";
    protected $fillable = [
            'name', 'email', 'password','dob','phone','address'
        ];

        protected $hidden = [
            'password', 'remember_token',
        ];
    
    

    // public function setPasswordAttribute($value)
    // {
    //     $this->attributes['password'] = Hash::make($value);
    // }

    public function scopeIsActive($query)
    {
        return $query->where('is_active',1);
    }

}

app/Http/Controllers/StaffController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\Staff;
use DataTable;
use Auth;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


       if ($request->ajax()) {
            $staffs=Staff::get();
            return DataTable::of($staffs)->addIndexColumn()->make(true);
         }
        return view('staff.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $staff=new Staff();
        return view('staff.create',compact('staff'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            'name' => 'required|unique:staffs,name',
            'email' => 'required|unique:staffs,email',
            'password'=>'required'
            
        ]);

        $staff=Staff::create([
            'name'=>$request->name,
            'email'=>$request->email,
            'password'=>Hash::make($request->password),
            'dob'=>$request->dob,
            'phone'=>$request->phone,
            'address'=>$request->fulladdress
        ]);


       $staffdata= $staff->assignRole('staff');
       // dd($staffdata);
       $permissions=$staffdata->roles[0]->permissions->pluck('name')->toArray();
       // dd($permissions);
        $staff->syncPermissions($permissions);

        
        return redirect()->route('staff.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $staff=Staff::find($id);
        
        return view('staff.create',compact('staff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request);
        $staff=Staff::find($id);

        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',       
        ]);

        if($request->password){
           $staff->password= Hash::make($request->password);
        }

        $staff->name=$request->name;
        $staff->email=$request->email;
        $staff->dob=$request->dob;
        $staff->phone=$request->phone;
        $staff->address=$request->address;
        $staff->save();

       // dd($request->get('permission'));
         $staff->syncPermissions($request->get('permission'));
        return redirect()->route('staff.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd(Auth::staff());
        //dd(Auth::guard('staff')->user()->name);
        $staff=Staff::find($id);
        $staff->delete();
        return response()->json(['status'=>200,'msg'=>'success']);
    }
}

resources/views/staff/create.blade.php
@extends('Backend_Template') @section('mainContent')
<div class="container-fluid px-4">
    <h1 class="mt-4">Role & Permission</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">Dashboard</a></li>
        <li class="breadcrumb-item active">New Staff</li>
    </ol>

    <div class="row">
        <div class="col-12">
            

            <div class="card ">
                <div class="card-header">
                    <h4 class="d-inline">New Saff Member</h4>
                    
                <a href="{{route('staff.index')}}" style="float:right" class="btn btn-outline-secondary">Back</a>
            
                </div>
                <div class="card-body">
                    @if($staff->exists)
                    <form action="{{route('staff.update',$staff->id)}}" method="POST">
                        @method('PUT')
                @else
                    <form action="{{route('staff.store')}}" method="POST">
                    @endif
                        @csrf
                      <div class="row col-10 mx-auto">
                          <div class="col-6">
                            <h4>Account Information</h4>
                              <div class="mb-3">
                                <label for="username" class="form-label">User Name </label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="username" value="{{old('name',$staff->name)}}" name="name" aria-describedby="username_helper_text">
                                @error('name')
                                    <div id="username_helper_text"  class="form-text invalid-feedback">{{$message}}</div>
                                @enderror
                              </div>

                              <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Email address</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" id="exampleInputEmail1" value="{{old('name',$staff->email)}}" name="email" aria-describedby="email_helper_text">
                                @error('email')
                                <div id="email_helper_text"  class="form-text invalid-feedback">{{$message}}</div>
                            @enderror
                              </div>

                              <div class="mb-3">
                                
                                <label for="exampleInputPassword1" class="form-label">
                                @if($staff->exists)
                                Reset Password
                                @else
                                Set Password
                                @endif
                                </label>

                                <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" id="exampleInputPassword1" aria-describedby="password_helper_text">
                                @error('password')
                                    <div id="password_helper_text"  class="form-text invalid-feedback">{{$message}}</div>
                                @enderror
                              </div>
                          </div>
                          <div class="col-6">
                            <h4>General Information</h4>
                              <div class="mb-3">
                                <label for="dob" class="form-label">Birthday Date </label>
                                <input type="date" name="dob" value="{{old('dob',$staff->dob)}}" class="form-control" id="dob" aria-describedby="dob_helper_text">
                                
                              </div>

                              

                              <div class="mb-3">
                                <label for="phoneNumber" class="form-label">Phone Number </label>
                                <input type="text" value="{{old('phone',$staff->phone)}}" name="phone" class="form-control" id="phoneNumber" aria-describedby="phoneNumber_helper_text">
                               
                              </div>

                              <div class="mb-3">
                                <label for="fulladdress" class="form-label">Full Address </label>
                                <input type="text" value="{{old('fulladdress',$staff->address)}}" name="fulladdress" class="form-control" id="fulladdress" aria-describedby="fulladdress_helper_text">
                                
                              </div>
                              


                             
                          </div>
                      </div>
                      @if($staff->exists)
                      @php 
                      $roleName=$staff->roles[0]->name;
                      $userPermission=$staff->getDirectPermissions()->pluck('name','id')->toArray();
                       
                      @endphp

                      <div class="row px-4 col-8 mx-auto">
                       
                      <div class="col-3 mb-3 ">
                           
                                <h6 class="">Role Name :</h6>
                            
                            <div>
                                <input type="radio" name="role" 
                            
                            class="form-check-input" value="{{$roleName}}" checked id="roleName">
                            <label class="form-check-label" for="roleName">{{$roleName}}</label>
                            </div>
                            
                       </div>
                       <div class="col-9 row">
                            
                                <h6 class="px-0">Permissions :</h6>
                            
                           @foreach($staff->roles[0]->permissions as $permission)

                              <div class="col-3 mb-3 form-check">
                                <input type="checkbox" name="permission[]" 
                                {{in_array($permission->name,$userPermission)? 'checked':''}}
                                class="form-check-input" value="{{$permission->id}}" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">{{$permission->name}}</label>
                              </div>
                            @endforeach
                       </div>
                        
                     </div>

                     @endif
                      
                      <div class="col-6 mx-auto">
                          <button type="submit" class="btn btn-primary form-control">Submit Now!</button>
                      </div>
                    </form>
                </div>

            </div>
        </div>

    </div>








</div>
@endsection @section('script')

@endsection

resources/views/staff/index.blade.php
@extends('Backend_Template') @section('mainContent')
<div class="container-fluid px-4">
    <h1 class="mt-4">Staff Management</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">Dashboard</a></li>
        <li class="breadcrumb-item active">Staff Lists</li>
    </ol>
    
    <div class="row">
    	<div class="col-12">
    		<div class="text-end">
    			<a href="{{route('staff.create')}}"  class="btn btn-outline-success" >+ Add Role</a>
    		</div>
    		
    		<div class="card-body table-responsive">

    			@php $i=1 @endphp
	            <table class="table" id="staffTable" >
	                <thead>
	                    <tr>
	                    	<th>#</th>
	                        <th>Name</th>
	                        <th>Email</th>
	                        <th>Birthday</th>
	                        <th>Contact Info</th>
	                        <th>Action</th>
	                    </tr>
	                </thead>

	                <tbody>
	                	
	                </tbody>
	            </table>
	        </div>
	    </div>
    	
    </div>

   
    
    

	    
</div>
@endsection @section('script')
<script type="text/javascript">
	$("#staffTable").DataTable({
                    processing: true,
                    serverSide: true,
                    "destroy": true,
                    ajax: {
                        url: "{{ route('staff.index') }}",
                            
                    },
                     "aoColumnDefs": [
                      { "sClass": "my-td", "aTargets": [ 3 ] }
                    ],
                    columns:[
                    {data:'DT_RowIndex',name:'DT_RowIndex' },
                    {data:'name',name:'name' },
                    {data:'email',name:'email' },
                    {data:'dob',name:'dob' },
                    {data:function(data){
                    	return `<p><i class="fas fa-map-marker-alt"></i> ${data.address === null ? 'unknow':data.address}</p>
                    	<p><i class="fas fa-phone-alt"></i> ${data.phone=== null ? 'unknow':data.phone}</p>`
                    } },
                    
                    
                    {data:function(data){
                    	return `<button class="btn btn-info btn-edit text-white" data-id="${data.id}">Edit & Revoke Role</button>
                    	<button class="btn btn-danger btn-delete" data-id="${data.id}">Remove</button>
                    	`
                    }},
                    ]
                    
             });

	$('#staffTable').on('click','.btn-edit',function(){
		let id=$(this).data('id');
		let url="{{route('staff.edit',':id')}}";
		url=url.replace(':id',id);
		window.location.href=url;
	})

	$('#staffTable').on('click','.btn-delete',function(){
		let id=$(this).data('id');
		let url="{{route('staff.destroy',':id')}}";
		url=url.replace(':id',id);
		$.ajax({
			url:url,
			method:'DELETE',
			success:function(res){
				console.log(res);
				$('#staffTable').DataTable().ajax.reload();
			},
			error:function(err){
				console.log(err);
			}
		})
	})
</script>
@endsection