routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FirebaseController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\BackendController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\StaffController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('home/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\FrontEndController@changeLang']);

Route::get('/mary', function () {
    return view('welcome');
});

Route::get('/hitit',[CityController::class,'sayhitit'])->name('hit.it');



Route::get('firebase', [FirebaseController::class, 'index']);
// Route::view('customers','customers'); 

//contact start
Route::resource('city', CityController::class);
Route::resource('contact', ContactController::class);



Route::group(['middleware' =>[ 'auth','role:customer']], function () {
    Route::get('/', function () {
    return view('FrontEnd_Template');
    });

//user route
Route::get('/user/order', [OrderController::class, 'orderCreatedByUser'])->name('user.order.create');
Route::get('/user/info', [FrontEndController::class, 'userInfo'])->name('user.info');
Route::get('/user/address/list', [FrontEndController::class, 'userAddressList'])->name('user.address.list');
Route::get('/user/order/list', [FrontEndController::class, 'userOrderList'])->name('user.order.list');

// order search --------
Route::post('/order/search', [FrontEndController::class, 'orderSearch'])->name('order.search');
Route::get('/user/home', [FrontEndController::class, 'userHomepage'])->name('user.home');

Route::get('/get/orders/{status}',[FrontEndController::class,'userOrderbyStatus'])->name('user.order.status');




Route::post('/order/store', [OrderController::class, 'orderStoredByUser'])->name('user.order.store');

Route::get('/order/{id}', [OrderController::class, 'orderDetail'])->name('user.order.detail');
// for user
Route::delete('/order/{id}', [OrderController::class, 'orderDestroy'])->name('order.delete');


    // excel import/export
Route::get('file/import/read',[OrderController::class,'UserImportfileReading'])->name('user.file.reading');
Route::get('file-import-export', [OrderController::class, 'fileImportExport']);
Route::post('file-import', [OrderController::class, 'fileImport'])->name('file-import');
Route::get('file-export', [OrderController::class, 'fileExport'])->name('file-export');
});



///admin start---------------------------------


Route::group(['middleware' => ['auth:web,staff','role:admin|staff','permission:order-status']],function(){

Route::post('/s/change/',[OrderController::class,'changeOrderStatus'])->name('order.status.change');

});







Route::group(['prefix'=>'admin','middleware'=>['auth:web,staff']],function () {




    Route::get('/dashboard', [BackendController::class, 'dashboard'])->name('dashboard.index');

    // customer start
    Route::prefix('/orders')->group(function () {

        Route::get('/', [BackendController::class, 'orderIndex'])->name('admin.order.list');


        Route::get('/create/new', [BackendController::class, 'orderCreate'])->name('admin.order.create');

        Route::get('/getAddressByuid/{id}', [BackendController::class, 'getAddressByuid'])->name('admin.order.getAddress');

        Route::get('/detail/{id}',[OrderController::class,'orderDetailByAdmin'])->name('admin.order.detail');

         Route::get('/edit/{id}',[OrderController::class,'orderEditByAdmin'])->name('admin.order.edit');

         Route::put('/update/{id}',[OrderController::class,'orderUpdateByAdmin'])->name('admin.order.update');

        Route::delete('/delete/{id}',[OrderController::class,'orderDeleteByAdmin'])->name('admin.order.destroy');

        Route::post('/date/filter',[OrderController::class,'orderDateFilter'])->name('admin.order.date.filter');

        Route::get('/import',[BackendController::class,'orderImport'])->name('admin.order.import');

         Route::post('/readExcel',[BackendController::class,'readExcel'])->name('admin.order.readExcel');

         Route::post('/importExcel',[BackendController::class,'importExcel'])->name('admin.order.importExcel');
    });

    Route::prefix('/address')->group(function () {
        Route::get('/create/{id}', [ContactController::class, 'addressCreateByUid'])->name('admin.address.createbyui');


        Route::get('/edit/{id}', [ContactController::class, 'addressEdit'])->name('admin.address.edit');

        Route::get('/getall/{id}', [ContactController::class, 'addressbyuserid'])->name('admin.userid.addresses');


    });

    // customer start
    Route::prefix('/customer')->group(function () {
        Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
    });

    Route::prefix('/rp')->group(function(){
        Route::get('/',[BackendController::class,'roleIndex'])->name('admin.rp.index');
        Route::get('/r/create',[BackendController::class,'roleCreate'])->name('admin.rp.role.create');
        Route::post('/r/store',[BackendController::class,'roleStore'])->name('admin.rp.role.store');
         Route::get('/r/show/{id}',[BackendController::class,'roleShow'])->name('admin.rp.role.show');
         Route::get('/r/edit/{id}',[BackendController::class,'roleEdit'])->name('admin.rp.role.edit');
         Route::put('/r/update/{id}',[BackendController::class,'roleUpdate'])->name('admin.rp.role.update');

         Route::delete('/r/destroy/{id}',[BackendController::class,'roleDelete'])->name('admin.rp.role.delete');


         Route::get('/p',[BackendController::class,'permissionIndex'])->name('admin.rp.p.index');

         Route::post('/p/store',[BackendController::class,'permissionStore'])->name('admin.rp.p.store');

         Route::put('/p/update/{id}',[BackendController::class,'permissionUpdate'])->name('admin.rp.p.update');

         Route::delete('/p/delete/{id}',[BackendController::class,'permissionDelete'])->name('admin.rp.p.delete');

    });

    //order import


});

//change order for admin and staff

// Route::group(['middleware'=>['auth','role:admin|staff','permission:publish order-status']],function () {
//         Route::get('/', [BackendController::class, 'customerIndex'])->name('admin.customer.index');
//     })



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');




require __DIR__ . '/auth.php';

// auth redireact

Route::get('/redirect', [ResponseController::class, 'index']);

Route::resource('staff',StaffController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,HasRoles;
    protected $guard_name='web';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/user/address_list_page.blade.php
@extends('FrontEnd_Template') @section('Manicontent')
<div class="titlebar">
    <div class="icon"><a href="{{ url()->previous()}}" style="color:#333;font-size: 1.5rem;"><i class="fas fa-chevron-left"></i></a></div>
    <div class="title">
        <h4>Address Management</h4>
    </div>
</div>
<div class="d-flex justify-content-center">
    <a href="{{ route('contact.create') }}" class="btn btn-outline-primary mt-3 my_cus_btn">
        <span> <i class="fas fa-plus"></i></span> Add New Recipient Address</a>
</div>
<div class="mt-2">
    <ul class="list-group">
        @foreach($contacts as $contact)
        <li class="list-group-item border-0">
            <div class="ms-2 me-auto">
                <div class="fw-bold">
                    <span style="color: #f44336"> No({{$contact->id}}).</span> {{$contact->full_address}}
                </div>
                {{$contact->city->name !== null ? $contact->city->name:'unknow city'}}
            </div>
            <div class="ms-2 me-auto mt-2">
                <form style="display: inline" method="POST" action="{{ route('contact.destroy',$contact->id) }}">
                    @csrf @method('delete')

                    <button type="submit" class="btn btn-danger">
                        {{ __("Remove") }}
                    </button>
                </form>
                <a href="{{ route('contact.edit',$contact->id) }}" class="btn btn-warning mx-2">Edit</a
                >
            </div>
        </li>
        <hr />
        @endforeach
    </ul>
</div>
@endsection @section('script')
<script>
    $(document).ready(function () {});
</script>
@endsection

resources/views/user/home.blade.php
@extends('FrontEnd_Template')
@section('Manicontent')
<section class="banner container-fluid"></section>
        <!-- banner end -->
        <div class="container p-4">
            <a
                href="{{ route('user.order.create') }}"
                class="btn btn-primary form-control"
                > {{__('Add Order')}}</a
            > 
            <a href="{{route('user.file.reading')}}" class="btn btn-primary form-control  mt-2 " >  @lang('Import Order') </a>

            <a class="btn btn-primary form-control d-none mt-2 import" > @lang('Import Order')</a>
            <form class="d-none" action="{{route('file-import')}}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="file" name="file" id="fileImport" >
            </form>
        </div>
@endsection
@section('script')
<script type="text/javascript">
    $('.import').click((e)=>{
        e.preventDefault();
        $('#fileImport').click();
    })

    $('#fileImport').change((e)=>{
        
        $('form').submit();
    })
</script>
@endsection

resources/views/user/info_page.blade.php
@extends('FrontEnd_Template') @section('Manicontent')

<div class="titlebar">
    <div class="icon"><a href="{{ route('user.home')}}" style="color:#333;font-size: 1.5rem;"><i class="fas fa-chevron-left"></i></a></div>
    <div class="title">
        <h4>{{__('Me')}}</h4>
    </div>
</div>
<div class="">
    <div class="user_info_div">
        <div class="avatar" style="
                background-image: url('https://cdn1.vectorstock.com/i/1000x1000/31/95/user-sign-icon-person-symbol-human-avatar-vector-12693195.jpg');
            "></div>
        <div class="user_info_content">
            <h3>{{Auth::check() ? Auth::user()->name :'unknown'}}</h3>
            <span>email:{{Auth::check() ? Auth::user()->email :'unknown'}}</span>
        </div>
    </div>
    <div>
        <ul class="list-group list-group-flush">
            <a style="text-decoration: none" href="{{ route('user.address.list') }}">
                <li class="list-group-item">
                    <div class="d-flex justify-content-between py-2">
                        <span>
                            <i class="fas fa-map-marker-alt"></i>
                            {{__('Address Management')}}
                        </span>
                        <div class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                </li>
            </a>
            <a>
                <li class="list-group-item">
                    <div class="d-flex justify-content-between py-2">
                        <span>
                            <i class="fas fa-headset"></i>
                           {{__('Contact Customer Service')}}
                        </span>
                        <div class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                </li>
            </a>
            <a>
                <li class="list-group-item">
                    <div class="d-flex justify-content-between py-2">
                        <span>
                            <i class="fas fa-bars"></i>
                            {{__('My Orders')}}
                        </span>
                        <div class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                </li>
            </a>
        </ul>
    </div>
    <div class="mt-3">
        <ul class="list-group list-group-flush">
            <a href="#exampleModal" style="text-decoration:none" data-bs-toggle="modal">
                <li class="list-group-item">
                    <div class="d-flex justify-content-between py-2">
                        <span>
                            <i class="fas fa-headset"></i>
                            {{__('Language')}}
                        </span>
                        <div class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                </li>
            </a>
            <a href="route('logout')" style="text-decoration: none" onclick="event.preventDefault();document.getElementById('logoutform').closest('form').submit();">
                <li class="list-group-item">
                    <div class="d-flex justify-content-between py-2">
                        <span>
                            <i class="fas fa-cog"></i>
                            {{__('Logout')}}
                        </span>
                        <div class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                </li>
                <form method="POST" id="logoutform" class="d-inline" action="{{ route('logout') }}">
                    @csrf
                </form>
            </a>
        </ul>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Language:{{ Config::get('languages')[App::getLocale()] }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">
        <ul class="list-group list-group-flush">
          
          @foreach (Config::get('languages') as $lang => $language)
        @if ($lang != App::getLocale())
        <li class="list-group-item">
                <a class="dropdown-item" href="{{ route('lang.switch', $lang) }}"> {{$language}}</a>
                </li>
        @endif
    @endforeach
        </ul>
      </div>
      
    </div>
  </div>
</div>

@endsection

resources/views/user/order_create.blade.php
@extends('FrontEnd_Template') @section('Manicontent')
<div class="titlebar">
    <div class="icon"><i class="fas fa-chevron-left"></i></div>
    <div class="title">
        <h4>{{__('New Order')}}</h4>
    </div>
</div>
<form class="px-2 mt-5" id="handleSubmit" autocomplete="off">
    @csrf

    <div class="mb-3 row">
        <label for="staticEmail" class="col-3 col-form-label">
            {{__('Warehouse')}}
        </label>
        <div class="col-9 cus-input-fromControl">
            <input type="text" readonly class="form-control-plaintext required" id="staticEmail" value="expresskoko" />
        </div>
    </div>
    <hr />
    <div class="mb-3 row">
        <label for="codes" class="col-3 col-form-label">
            {{__('China logistic number')}}
        </label>
        <div class="col-9 cus-input-fromControl" style="display: block;">
            <input type="text" class="form-control-plaintext required countQty" id="codes" name="codes" placeholder="Please enter china logistic number" />
            <span style="color:#333;font-size: 0.725rem;">Note:  please use ',' if you got more than one. example: 123,345,345</span>
        </div>
    </div>
    <hr />

    <div class="mb-4 row">
        <label for="contact" class="col-3 col-form-label"> {{__('Address')}} </label>
        <div class="col-9 addressForm">
            <select id="contact" class="form-select required" aria-label="Default select example " name="contact_id">
                <option value="0" selected>{{__('Please choose one')}}</option>
                @foreach($contacts as $k=>$contact)
                <option value="{{$contact->id}}">
                    No({{$contact->id}}) .
                    {{$contact->full_address}},{{$contact->city->name}}
                </option>
                @endforeach
            </select>
            <a href="{{ route('contact.create') }}" class="btn btn-light">+</a>
        </div>
    </div>

    <hr />
    <div class="mb-3 row">
        <label for="name" class="col-3 col-form-label"> {{__('Recipient Name')}} </label>
        <div class="col-9 cus-input-fromControl">
            <input type="text" class="form-control-plaintext required" id="name" name="name" placeholder='{{__("plases enter Recipient Name")}}'/>
        </div>
    </div>
    <hr />

    <div class="mb-3 row">
        <label for="phone" class="col-3 col-form-label">
            {{__('Recipient phone number')}}
        </label>
        <div class="col-9 cus-input-fromControl">
            <input type="number" class="form-control-plaintext required" id="phone" name="phone" placeholder="please enter Recipient phone number" />
        </div>
    </div>
    <hr />

    <div class="mb-3 row">
        <label for="Goodsqty" class="col-3 col-form-label">
            {{__('Numbers of Box')}}
        </label>
        <div class="col-9 cus-input-fromControl">
            <input type="number" class="form-control-plaintext required" id="Goodsqty" name="qty" placeholder="please enter good number" />
        </div>
    </div>
    <hr />
    <div class="mb-3 row">
        <label for="wieight" class="col-3 col-form-label"> {{__('Total Weight')}} </label>
        <div class="col-9 cus-input-fromControl">
            <input type="number" class="form-control-plaintext required" id="weight" name="weight" placeholder="please enter good total wieight" />
            <h6>{{__('Kg')}}</h6>
        </div>
    </div>
    <hr />
    <div class="mb-3 row">
        <label for="goodNames" class="col-3 col-form-label"> {{__('Goods Name')}} </label>
        <div class="col-9 cus-input-fromControl">
            <input type="text" class="form-control-plaintext" id="goodNames" name="goodsNames" placeholder="please enter good names" />
        </div>
    </div>
    <hr />
    <div class="mb-3 row">
        <label for="price" class="col-3 col-form-label">
            {{__('Prices of Goods')}}
        </label>
        <div class="col-9 cus-input-fromControl">
            <input type="text" class="form-control-plaintext required" id="price" name="price" placeholder="please enter total price of Goods" />
        </div>
    </div>
    <input type="submit" value="Order Now" class="btn btn-primary form-control" />
</form>
@endsection
@section('script')
<script>
    const errors = {
        codes: "Please enter china logistic number",
        contact_id: "Please Choose Recipient Address",
        name: "Please enter Recipient Name",
        phone: "Please enter Recipient Phone number",
        weight: "Please enter Total Good Wieight",
        goodsNames: "Please enter good names",
        price: "Please enter price",
    };

    function getoldValue() {
        let order = localStorage.getItem("order");
        if (order) {
            let orderObj = JSON.parse(order);
            for (const key in orderObj) {
                if (orderObj.hasOwnProperty(key)) {
                    if (key === "contact_id") {
                        $(`select[name="${key}"]`).val(orderObj[key]);
                    } else {
                        $(`input[name="${key}"]`).val(orderObj[key]);
                    }
                }
            }
        }
    }
    $(document).ready(function() {
        getoldValue();
        $('input[type="text"]').keyup(function(e) {
            const {
                name,
                value
            } = e.target;
            //    console.log(name);
            let order = localStorage.getItem("order");

            if (!order) {
                let orderItem = {
                    codes: "",
                    contact_id: "0",
                    name: "",
                    phone: "",
                    goodsNames: "",
                    qty: "",
                     weight: "",
                    price: "",
                };
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };
                localStorage.setItem("order", JSON.stringify(orderItem));
            } else {
                let orderItem = JSON.parse(order);
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };

                localStorage.setItem("order", JSON.stringify(orderItem));
            }
        });
        $('input[type="number"]').keyup(function(e) {
            const {
                name,
                value
            } = e.target;
            //    console.log(name);
            let order = localStorage.getItem("order");

            if (!order) {
                let orderItem = {
                    codes: "",
                    contact_id: "",
                    name: "",
                    phone: "",
                    qty: "",
                    weight: "",
                    goodsNames: "",
                    price: "",
                };
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };
                localStorage.setItem("order", JSON.stringify(orderItem));
            } else {
                let orderItem = JSON.parse(order);
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };

                localStorage.setItem("order", JSON.stringify(orderItem));
            }
        });
        $("select").change(function(e) {
            const {
                name,
                value
            } = e.target;
            let order = localStorage.getItem("order");

            if (!order) {
                let orderItem = {
                    codes: "",
                    contact_id: "",
                    name: "",
                    phone: "",
                    qty: "",
                    weight: "",
                    goodsNames: "",
                    price: "",
                };
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };
                localStorage.setItem("order", JSON.stringify(orderItem));
            } else {
                let orderItem = JSON.parse(order);
                orderItem = {
                    ...orderItem,
                    [name]: value,
                };

                localStorage.setItem("order", JSON.stringify(orderItem));
            }
        });

        $("#handleSubmit").submit(function(e) {
            // action="{{ route('user.order.store') }}" method="post"
            let hasError = checkError();
            //console.log(checkError());

            var formdata = $(this).serialize();
            // console.log(form);

            if (!hasError) {
                console.log("error");
            } else {
                $.ajax({
                    url: "{{ route('user.order.store') }}",
                    method: "post",
                    data: formdata,
                    success: function(response) {
                        if (response.status == 200) {
                            localStorage.removeItem("order");
                            window.location.href = "/user/order/list";
                        }
                    },
                    error: function(err) {
                        console.log(err);
                    },
                });
            }
            e.preventDefault();
        });
    });

    // auto countiing

    $(".countQty").keyup(function(e) {
        var {
            value
        } = e.target;
        let data = value.split(",");

        let count = data.length;
        if (data[count - 1] == "") {
            count = data.length - 1;
        } else {
            count = count;
        }

        $("#Goodsqty").val(count);

        let order = localStorage.getItem("order");

        if (!order) {
            let orderItem = {
                codes: value,
                contact_id: "",
                name: "",
                phone: "",
                qty: count,
                weight: "",
                goodsNames: "",
                price: "",
            };

            localStorage.setItem("order", JSON.stringify(orderItem));
        } else {
            let orderItem = JSON.parse(order);
            orderItem.codes = value;
            orderItem.qty = count;
            localStorage.setItem("order", JSON.stringify(orderItem));
        }

        // let order = localStorage.getItem("order");

        // let obj = JSON.parse(order);
        // obj.qty = count;
        // localStorage.setItem("order", JSON.stringify(obj));
    });

    function checkError() {
        $(".required").each(function(i, el) {
            const {
                name,
                value,
                type
            } = el;

            if (value == "") {
                showError(errors[name]);
                return false;
            } else {
                // console.log('helo');
                if (value == 0) {
                    showError(errors[name]);
                    return false;
                }
            }
        });

        return true;
    }

    function showError(text) {
        Swal.fire({
            text: `${"{{__("+text+")}}"}`,
            showConfirmButton: false,
            timer: 2000,
            showClass: {
                popup: "slow-animation",
            },
            hideClass: {
                popup: "slow-animation-2",
            },
        });
    }
</script>
@endsection

resources/views/user/order_detail.blade.php
@extends('FrontEnd_Template') @section('Manicontent')
<div class="my-card">
    <div class="my-card-header">
      <div class="titlebar">
    <div class="icon"><a href="{{ url()->previous()}}" style="color:#333;font-size: 1.5rem;"><i class="fas fa-chevron-left"></i></a></div>
    <div class="title">
        <h4>Order Detail ({{$order->code}})</h4>
    </div>
</div>


        
    </div>
    <div class="card-body">
        @php

         $colors = [
          1=> "#ff0000",
          2=>"#2196f3",
          3=> "#5417c1",
          4=> "#03ad0a",
          ];

         @endphp
         <h5>Order Detail</h5>

        <div class="detail-grid">
            <div>{{__('Order Code')}}</div>
            <div>:{{ $order->order_code }}</div>

            <div>{{__('China logistic code')}}</div>
            <div> :{{ $order->code }}</div>

            <div>{{__('Order Date')}}</div>
            <div> :{{ $order->order_date }}</div>

            <div>{{__('Status')}}</div>
            <div >:<span class="status" style="color: {{$colors[$order->status->id]}}">{{ $order->status->name }}</span></div>

            <div>{{__('Update Date')}}</div>
            <div> :{{ $order->updated_at }}</div>


            <div>{{__('Recipient Names')}}</div>
            <div> :{{ $order->recipient_name }}</div>

            <div>{{__('Recipient Phone')}}</div>
            <div> :{{ $order->phone }}</div>

            <div>{{__('Recipient Address')}}</div>
            <div> :{{ $order->contact->full_address }}</div>

            
        </div>
        <div class="d-flex justify-content-around gap-1 mt-2">
            <button class="btn">...</button>
            <form style="" method="POST" action="{{ route('order.delete', $order['id']) }}">
                @csrf @method('delete')

                <button type="submit" class="btn btn-outline-danger">
                    {{ __("Delete Order") }}
                </button>
            </form>
            <button class="btn btn-outline-dark">
                Contact customer service
            </button>
        </div>
    </div>
</div>
@endsection